title: Stackbit Starter Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: An ultra customizable generic theme for Stackbit
header:
  title: Basilicous
  has_nav: true
  nav_links:
    - label: Features
      url: /features
      style: link
    - label: Blog
      url: /blog
      style: link
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Contact Us
      url: /contact
      style: primary
footer:
  has_nav: true
  nav_links:
    - label: Contact Us
      url: /contact
      style: link
    - label: Privacy and Terms
      url: /terms
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/basilicous'
      style: link
      new_window: true
    - label: GitHub
      url: 'https://github.com/LowSpecCorgi'
      style: link
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: link
      new_window: true
  content: "LMFAO\_ STACKBIT DID YOU THINK YOU COULD PUT YOUR FUCKING WATERMARK HERE. TRY HARDER PUSSY."
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
